[profile.default]
libs = ["lib"]
out = "out"
remappings = [
  "/solmate=/lib/solmate/src",
  "@prb/math/=lib/prb-math/src/",
  "solstat=/lib/solstat/src",
]
solc_version = "0.8.19"
src = "src"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fmt]
bracket_spacing = true
int_types = 'long'
line_length = 80
multiline_func_header = 'params_first'
quote_style = 'double'
tab_width = 4
wrap_comments = false
