[profile.default]
remappings = [
    "solstat/=lib/solstat/src/",
    "forge-std/=lib/solstat/lib/forge-std/src/",
    "solmate/=lib/solstat/lib/solmate/src/",
]
solc_version = "0.8.22"
bytecode_hash = "none"
cbor_metadata = false
extra_output = ["storageLayout"]
via_ir = false

# these are defaults. explicitly setting them here for clarity.
libs = ["lib"]
out = "out/"
src = "src/"
test = "src/test/"

[fmt]
bracket_spacing = true
int_types = 'long'
line_length = 80
multiline_func_header = 'params_first'
quote_style = 'double'
tab_width = 4
wrap_comments = false
number_underscore = "thousands"

[rpc_endpoints]
local = "http://localhost:8545"
