[package]
name = "box-core"
version = "0.1.0"
edition = "2021"

[[library]]
name = "box_core"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
